Url validation
DSusol/urlshortener pull request #15
Opened 2022-06-06 17:50 UTC by DSusol

2022-06-06 19:10 UTC, tkachenkoas requested changes
Валидацию нужно делать в сервисном слое, кидать эксепшн и ловить его где-то в бото-слое, а потом транслировать в сообщение для пользователя

таким образом ты сможешь прикручивать другие каналы поставки урл-ов, и тебе не придется копипастить логику валидации - вместо этого ловить исключение и как-то конвертить его в пользователечитаемый вид

2022-06-06 19:10 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/bot/utils/message/MessageHandler.java
> +    SendMessage prepareSendMessage(Long chatId, String template);
мне постфикс имени Handler как-то не очень нравится... он же по сути ничего не хэндлит, а делает вспомогательную работу...

MessageUtil ?..

ну и кстати учитывая, что все методы однострочные, может имеет смысл вообще убрать интерфейс - много чести :)

2022-06-06 19:10 UTC, tkachenkoas commented on src/main/resources/messages/messages_ru.properties
> +new.link.command.invalid.url=некоррекстный url, попробуйте ещё раз:
"некоррекстный" опечатка

2022-06-06 19:10 UTC, tkachenkoas commented on src/main/resources/messages/messages.properties
> +new.link.command.invalid.url=invalid url provided, please try again:
А что у тебя половина сообщений с большой буквы, а другая с маленькой?

I'm -> погугли, как одинарную кавычку правильно заэскейпить

2022-06-06 19:10 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/bot/commands/main/CreateNewLinkFlowTest.java
> +    void when_bot_is_not_able_to_make_url_shorter_then_send_related_message() {
у тебя может быть 100500 валидаций с разными правилами, не надо их все гонять через интеграционный тест (заебёшьсо подстраивать инпуты чтобы всякие хитрые граничные кейсы проверить, и тест будет перегружен низкоуровневыми деталями)

у тебя уже есть кейс "when_invalid_url_name_is_provided_should_ask_for_another_input" - он по сути верифицирует, что в целом валидация у тебя работает (т.е. код пробегает через валидатор)

а все тонкости валидации нужно юнит-тестить - и тогда на интеграционном уровне всё тоже будет работать by-design

2022-06-07 09:49 UTC, DSusol commented on src/main/java/com/learning/urlshortener/bot/commands/main/create_new_link/validation/UrlValidationStatus.java
> +public enum UrlValidationStatus {
со вторым не разобрался что надо сделать

2022-06-07 10:29 UTC, DSusol commented on src/main/java/com/learning/urlshortener/bot/commands/main/create_new_link/validation/UrlValidation.java
> +                .map(UValidator::getUrlValidationStatus)
Согласен, но у меня природа проверок разная (ошибка инпута vs проверка бота на возможность сделать ссылку короче).. не логично ведь будет получить такой ответ:

user: 
`- на говноинпут`

bot:
`- ты мне подсовываешь говноинпут`
`- сорян, я не могу сделать твоё говнище короче, тк использую бесплатный домейн`

2022-06-07 18:50 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/bot/commands/main/create_new_link/CreateNewLinkCommandExecutor.java
> +    private void processNonValidUrl(UrlValidationResult validationResult, ChatMetaData metaData) throws TelegramApiException {
используй @ SneakyThrows чтобы все эти ```throws TelegramApiException``` не тащить

зафейлится - ок, подумаем, как и где обработать. не упадет - ещё лучше

2022-06-09 19:22 UTC, tkachenkoas approved these changes
мой котёл плавится уже...

делай что хочешь,

2022-06-09 19:22 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/bot/commands/main/create_new_link/executors/CreateNewLinkCommandState.java
> +public enum CreateNewLinkCommandState implements CommandState {
ещё раз повторю мысль свою:
- паттерн нужно херачить сразу когда у тебя разные "ветки" логики - то есть например разные команды, которые вообще никак не связаны друг с другом
- когда у тебя одна команда в несколько шагов - напиши всё в одном классе в два приватных метода...

2022-06-09 19:22 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/bot/commands/main/create_new_link/executors/DuplicateUrlStateExecutor.java
> +        if (response.equals(noAnswer)) {
в телеграме кнопки для этого есть... ну почему ты меня не спрашиваешь, прежде чем "Войну и мир" писать?.. :)

2022-06-09 19:22 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/bot/commands/main/create_new_link/executors/StartStateExecutor.java
> +        } catch (UrlSyntaxValidationException urlSyntaxValidationException) {
ещё можно сделать один эксепшн и у  него какой-нибудь код ошибки в сообщении 

по типу того как апи фейсбука возвращает ответы https://developers.facebook.com/docs/instagram-api/reference/error-codes/

2022-06-09 19:22 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/bot/commands/main/create_new_link/executors/StartStateExecutor.java
> +                exception instanceof UrlSyntaxValidationException, "new.link.command.invalid.url",
instanceof это зашквар, особенно как ключ в мапе.
```exception.getCode()``` красивее бы смотрелось - код брошенный сервисом ты бы мапил на сообщение сразу

2022-06-09 19:22 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/bot/commands/main/state/ChatMetaData.java
>      private String message;
откуда месседж взялся к чат стейте.... что это за поле вообще?

2022-06-09 19:22 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/bot/commands/main/state/ChatMetaData.java
> +    private CommandState commandState;
у тебя получается енум комман-стейт будет знать все стейты все команд - это неправильно.
что такое аргз?

сделай одно поле - ```Map<String, String> stateMetaData``` - и пусть каждый команд процессор кладёт в эту мапу любое говно, которое он сам понимает. а когда другому процессору передадут, всё равно всё сбросят.

2022-06-09 19:22 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/services/UrlShortenerService.java
> +    Link saveNewLink(Customer customer, String url, boolean duplicateAllowed) throws UrlValidationException;
boolean в аргументах метода это харам.

https://medium.com/@amlcurran/clean-code-the-curse-of-a-boolean-parameter-c237a830b7a3
https://martinfowler.com/bliki/FlagArgument.html

зачем, зачем ты придумал эту фичу?...

2022-06-09 19:22 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/services/UrlShortenerServiceImpl.java
> +        List<Link> links = linkDAO.findLinksByCustomerAndUrl(customer, url);
нафига тащить все линки из базы если тебе только проверить надо, что они есть?

count сделай или exists

2022-06-09 19:22 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/services/urlvalidation/UrlValidators.java
> +public interface UrlValidators {
пожалуйста, сделай все валидации в одном классе... =)

2022-06-09 19:22 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/services/urlvalidation/validators/UrlLengthValidator.java
> +@Order(2)
вот ордер это критически важное? без него совсем работать не будет?

2022-06-10 18:23 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/services/UrlShortenerService.java
> +    Link saveValidatedNewLink(Customer customer, String url);
а что, этот типа не выбросит эксепшун, если в него какашку кинуть? :)

чем валидейтед отличается от просто нью?

2022-06-10 18:24 UTC, tkachenkoas approved these changes
мерж уже, потом будем подпиливать

2022-06-10 19:01 UTC, merged