Repositories
DSusol/urlshortener pull request #4
Opened 2022-04-27 16:14 UTC by DSusol

2022-04-27 19:12 UTC, tkachenkoas requested changes
без тестов апрува не получишь -> гугли @-DataJpaTest

2022-04-27 19:12 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/domains/Customer.java
> +    @OneToMany(cascade = CascadeType.ALL, mappedBy = "customer", fetch = FetchType.EAGER)
Зачем Eager? есть миллион кейсов, когда кастомера нужно загружать без линков.

2022-04-27 19:12 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/domains/Customer.java
> +public class Customer {
нормальные пацаны ещё пишут название таблицы

2022-04-27 19:12 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/domains/Customer.java
> +    private String nickname;
нормальные пацаны делают аннотации с названиями полей таблицы @Field("nick_name")

2022-04-27 19:12 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/domains/Customer.java
> +    private String password;
емейл и пассворд выкидывай в пень. 
до аутентификации пока еще не доросли. начнем с фич, относящихся к телегоботу

ну и вообще пароли в базе никто не хранит. не лезь на 100 километров вперед - больше переделывать придется

2022-04-27 19:12 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/domains/Link.java
> +@Setter
да сделай ты уже @-Data и не парься

2022-04-27 19:12 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/domains/Link.java
> +    private Customer customer;
зачем тебе при каждой загрузке линка грузить еще и кастомера?

2022-04-27 19:12 UTC, tkachenkoas commented on src/main/resources/application-dev.yml
> +spring:
лучше сделай .properties файл. ямл сложнее для восприятия и используется реже.
а еще там если сраный таб неправильно поставишь, ничего работать не будет

2022-04-27 19:12 UTC, tkachenkoas commented on src/main/resources/application-dev.yml
> +    username: sa
для h2 не нужны юзер-пароли по-моему, там всё авто-конфигурациями ставится...

2022-04-27 19:12 UTC, tkachenkoas commented on src/main/resources/application-prod.yml
> +        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
поверь суровому техлиду: лучше все нейминги прописывать аннотациями - так не ошибешься

2022-04-27 19:12 UTC, tkachenkoas commented on src/main/resources/application.properties
> +spring.profiles.active=dev
ноуп. профайлы обычно задаются через системные переменные, а не через проперти-файл

можно в грейдле сконфигурировать себе специальный "bootRun" таск 

task runLocalApp {
    group = 'application'
    bootRun.configure {
        systemProperty "spring.profiles.active", 'dev'
    }
    finalizedBy bootRun
}

2022-04-27 19:12 UTC, tkachenkoas commented on src/main/resources/scripts/spring_database_create.sql
> +create table customer (id  bigserial not null, email varchar(255), nickname varchar(255), password varchar(255), primary key (id));
изучаем ликвибейз: https://www.techgeeknext.com/spring-boot/spring-boot-liquibase-sql-example

2022-04-27 19:15 UTC, tkachenkoas commented on src/main/resources/application-dev.yml
> +    username: sa
а вообще на потом - dev профайл должен быть сконфигурирован на докер постгреса, чтобы все твои локальные игры у тебя оставались после рестарта :)

2022-04-27 19:16 UTC, tkachenkoas commented
а также дай мне админ права на репозиторий :)

2022-04-28 09:45 UTC, DSusol commented on src/main/java/com/learning/urlshortener/domains/Customer.java
> +package com.learning.urlshortener.domains;
Хорошо, тогда мне нужно понять где они будут. Я думал, что домейны для этого и созданы

2022-04-28 09:57 UTC, DSusol commented on src/main/java/com/learning/urlshortener/domains/Link.java
> +@Setter
неявное EqualsAndHashCode - это разве хорошо?

2022-04-28 10:23 UTC, DSusol commented on src/main/resources/application-prod.yml
> +        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
а есть такое место для аннотации, где это можно было бы прописать единожды?

2022-04-28 10:30 UTC, DSusol commented on src/main/resources/application.properties
> +spring.profiles.active=dev
в чём преимущество грейдл-конфигурации, над проперти-файлом?

2022-04-28 13:00 UTC, DSusol commented on src/main/resources/scripts/spring_database_create.sql
> +create table customer (id  bigserial not null, email varchar(255), nickname varchar(255), password varchar(255), primary key (id));
не получилось настроить..

2022-04-29 15:57 UTC, tkachenkoas reviewed
грейдл-враппер jar не нужно комитить в репозиторий - он весит дохера, но скачается автоматически в соотвествии с gradle.properties (ну или где там версия указывается...)

2022-04-29 15:57 UTC, tkachenkoas commented on build.gradle
> +	configFile file("${project.rootDir}/path/to/checkstyle/config/checkstyle.xml") // Checkstyle config location
path/to/checkstyle ???

также я думаю, что большая часть остальных конфигов не нужна, они дефолтные

2022-04-29 15:57 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/bootstrap/DataLoader.java
> +        if (userRepository.findAll().size() == 0 || linkRepository.findAll().size() == 0) {
userRepository.count()

2022-04-29 15:57 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/entities/CustomerEntity.java
> +    @OneToMany(cascade = CascadeType.ALL, mappedBy = "customer")
CascadeType.ALL очень плохая форма каскада...

послушай Алименкова, он там поясняет про всякие изменения в хибернейте...

1) не факт что у тебя процесс апдейта ссылок будет через сохранение кастомера
2) когда у кастомера 1000 ссылок, есть риск того что любое изменение кастомера ещё отправит тыщу запросов на апдейт ссылок - просто за счет логики каскада... :)

но это так, рассуждения... нужно будет прогонять реальные тесты и смотреть реальные запросы, которые летят в базу

2022-04-29 15:57 UTC, tkachenkoas commented on src/main/resources/application-dev.properties
> +spring.jpa.hibernate.ddl-auto=update
ты знаешь, что делает эта проперти?

2022-04-29 15:57 UTC, tkachenkoas commented on src/main/resources/application-dev.properties
> +spring.jpa.show-sql=true
лучше для дева убери это - это только для тестов полезная проперти когда ты пишешь свои сценарии и изучаешь, что там за запросы летят в базу

2022-04-29 15:57 UTC, tkachenkoas commented on src/main/resources/application-prod.properties
> +spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
продакшен логи собрался засирать своими запросами? =)

2022-04-29 15:57 UTC, tkachenkoas commented on src/main/resources/application-prod.properties
> +spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect - подвинь в дефолтный application.properties

также - изучи вот это
https://docs.spring.io/spring-boot/docs/1.5.10.RELEASE/reference/html/boot-features-external-config.html

2022-04-29 15:57 UTC, tkachenkoas commented on src/main/resources/db/changelog/changelog.sql
> +CREATE TABLE customer
лучше каждое изменение на отдельный чейнджсет делать

2022-04-29 15:57 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/repositories/CustomerRepositoryTest.java
> +import static org.junit.jupiter.api.Assertions.assertNull;
я тебе очень серьезно рекомендую пользовать Asserttions.assertThat из библиотеки assertj - там прям очень крутой апи...
она специализируется на всяких формах ассертов - а org.junit.jupiter.api.Assertions - это так, побочный класс фреймворка...

2022-04-29 15:57 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/repositories/CustomerRepositoryTest.java
> +    void should_find_all_customers() {
этот тест тестирует спринговый репозиторий. нет ни одной строчки твоего кода, который ты можешь сломать, чтобы этот тест упал (а остальные при этом не упали)

но если бы репозитории были обернуты в DAO, этот тест бы имел право на жизнь (т.к. ты верифицируешь, что твой DAO класс поддерживает удаление)

2022-04-29 15:57 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/repositories/CustomerRepositoryTest.java
> +    void should_save_all_customers() {
тот же коммент как и с каунт -> нет ни одной строчки твоего кода, которая покрывается этим тестом

2022-04-29 15:57 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/repositories/LinkRepositoryTest.java
> +    void should_find_no_link_if_repository_is_empty() {
комментарии скорее всего будут аналогичны кастомер репозиторию

2022-04-30 08:45 UTC, DSusol commented on src/main/resources/application-dev.properties
> +spring.jpa.hibernate.ddl-auto=update
Вроде всё правильно:

The update operation will query the JDBC driver's API to get the database metadata and then Hibernate compares the object model it creates based on reading your annotated classes or HBM XML mappings and will attempt to adjust the schema on-the-fly.
The update operation for example will attempt to add new columns, constraints, etc but will never remove a column or constraint that may have existed previously but no longer does as part of the object model from a prior run.
In development, it's often common to see developers use update to automatically modify the schema to add new additions upon restart. But again understand, this does not remove a column or constraint that may exist from previous executions that is no longer necessary.

2022-04-30 09:09 UTC, DSusol commented on src/main/resources/application-prod.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
я до того момента оставлю, чтобы профаил запускался

2022-04-30 17:56 UTC, tkachenkoas requested changes

2022-04-30 17:56 UTC, tkachenkoas commented on build.gradle
> +	testImplementation group: 'org.assertj', name: 'assertj-core', version: '3.11.1'
она приходит вместе со спринг-бут-стартер-тест

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/domain/Customer.java
> +
ну на самом деле айдишник нужен будет... тебе же надо, чтобы внешний мир как-то ссылался на кастомера

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/domain/Link.java
> +
а вот тут возможно айдишник и не нужен... ибо шортенед урл вроде почти как айдишник

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/domain/Link.java
> +    private String url;
ещё полезно на доменной модели писать джавадок - что вообще эти поля означают в рамках общей логики.

в твоем случае ещё какие-то примеры можно привести - как выглядит шортенед урл и урл :)

также нужно умонять, что изменяемое - а что не изменяемое

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/services/LinkDaoService.java
> +public interface LinkDaoService {
LinkDAO

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/resources/application-dev.properties
> +spring.jpa.hibernate.ddl-auto=update
так, а па-рузке, чтобы даже такой тупой пень как я понял?

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/entities/CustomerEntity.java
> +    @OneToMany(cascade = CascadeType.ALL, mappedBy = "customer", fetch = FetchType.EAGER)
ты прям на 100% уверен, что абсолютно все операции загрузки кастомера также требуют загрузки всех его линков?

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/services/CustomerDaoServiceImpl.java
> +@Service
это не сервис, а @Repository

это не компонент бизнес-логики, а обертка над низкоуровневыми spring-repository, которая задает операции на уровне базы

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/services/CustomerDaoServiceImpl.java
> +    public CustomerDaoServiceImpl(CustomerRepository customerRepository,
можно заменить на @-AllArgsConstructor

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/services/CustomerDaoServiceImpl.java
> +package com.learning.urlshortener.services;
com.learning.urlshortener.database

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/services/CustomerDaoService.java
> +public interface CustomerDaoService {
CustomerDAO. Это не сервис - Data Access Object (storage access object)

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/services/LinkDaoServiceImpl.java
> +        LinkEntity linkEntityToSave = linkMapper.linkToLinkEntity(link);
34 и 35 лучше поменять местами

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/services/LinkDaoServiceImpl.java
> +        return linkMapper.linkEntityToLink(linkRepository.save(linkEntityToSave));
я обычно так форматирую вложенные вызовы

```
linkMapper.linkEntityToLink(
    linkRepository.save(linkEntityToSave)
)
```

2022-04-30 17:56 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/mappers/CustomerMapperTest.java
> +import static org.junit.jupiter.api.Assertions.assertNotNull;
ты уже выбери одну либу :)

2022-04-30 17:56 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/services/BaseDBTest.java
> +@ComponentScan("com.learning.urlshortener.mappers")
сделай один пакадж для базы - ```com.learning.urlshortener.database``` и положи всё в него

а ещё лучше группировать не по "repositories/entities/mappers", а по фичам - "customer/links"

2022-04-30 17:56 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/services/CustomerDaoServiceImplTest.java
> +    TestEntityManager entityManager;
не-а, все операции - исключительно через твои DAO - ровно так, как будет приложение использовать
Никаких репозиториев, мапперов и энтитименеджеров

2022-04-30 17:56 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/services/CustomerDaoServiceImplTest.java
> +    CustomerDaoService serviceUnderTest;
вот почему не просто "андерТест"? :)

2022-04-30 17:56 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/services/CustomerDaoServiceImplTest.java
> +        entityManager.persist(customerMapper.customerToCustomerEntity(existingCustomer));
не лезь в кишки имплементаций. Твои тесты должны меняться только если поменяется твой интерфейс.

Даже если ты вдруг поменяешь базу данных - твои интерфейсы ДАО, как и тесты - не должны меняться

2022-04-30 17:56 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/services/LinkDaoServiceImplTest.java
> +    TestEntityManager entityManager;
аналогичные комментарии - убери кишки из тестов, все операции гони только через интерфейсы

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/mappers/LinkMapper.java
> +public interface LinkMapper {
лучше назвать LinkEntityMapper

2022-04-30 17:56 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/entities/LinkEntity.java
> +    @Column(name = "shortened_url", unique = true)
шо-то я не нашел тест на это... есть он у тебя?

2022-04-30 18:58 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/domain/Link.java
> +
но вообще у модели, которая будет сохраняться в бд, в 99% случаев нужен айдишник.

2022-05-01 23:23 UTC, DSusol commented on src/main/java/com/learning/urlshortener/entities/CustomerEntity.java
> +    @OneToMany(cascade = CascadeType.ALL, mappedBy = "customer", fetch = FetchType.EAGER)
нет, это я тестил и забыл убрать..

2022-05-02 22:34 UTC, tkachenkoas requested changes
как видишь, новые вопросы всё появляются и появляются :)

и ещё один на засыпку: а сколько транзакций происходит в твоих тестах? :)

2022-05-02 22:34 UTC, tkachenkoas commented on src/main/resources/db/changelog/changelog.sql
> +    ADD CONSTRAINT nickNameConstrain UNIQUE (nick_name);
google search -> "db constraint naming convention"

https://www.c-sharpcorner.com/UploadFile/f0b2ed/what-is-naming-convention/#:~:text=The%20naming%20convention%20for%20a%20check%20constraint%20is%3A,and%20ColumnName%20should%20be%20capitalized.

а ещё доп вопрос: что там по nullability полей?

2022-05-02 22:34 UTC, tkachenkoas commented on src/main/resources/db/changelog/changelog.sql
> +    customer      INT8,
что-то у тебя у customer здесь и в таблице кастомера разный тип...

2022-05-02 22:34 UTC, tkachenkoas commented on src/main/resources/db/changelog/changelog.sql
> +    url           VARCHAR(255),
кто-то может захотеть сохранить ссылку подлиннее чем 255 с query-параметрами (типа поиск яндекс-маркета - проверь какой-нибудь хитрый запрос и глянь, какая там длина выходит)

ну а сокращенная ссылка наверное максимум 64 займет вместе с доменом?

2022-05-02 22:34 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/database/customers/CustomerDAOImplTest.java
> +                        () -> underTest.findCustomerById(existingCustomerId));
строчки 72 и 75 вообще не обязательны :) можно было просто рандомный айдишник использовать :)

2022-05-02 22:34 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/database/customers/CustomerDAOImplTest.java
> +        Long link1Id = linkDAO.saveLink(existingCustomer, new Link()).getId();
сразу порекомендую вместо new Link() использовать SimpleTestObjectFactory.simpleLink()

которая будет создавать простенький объект со всеми обязательными полями. а то стоит добавить non-null на уровне базы, и всё взорвется :)

2022-05-02 22:34 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/database/customers/CustomerDAOImplTest.java
> +        assertThatExceptionOfType(RuntimeException.class)
в целом, лишнее условие :) если первую снесло - то и вторую вряд ли пощадило :)

2022-05-02 22:34 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/database/links/LinkDAOImplTest.java
> +                .extracting("shortenedUrl", "url", "clickCount")
"строкотипизация" :)

там есть операция типа "isEqualToIgnoringGivenFields" ... (который тоже попросит указать поля для игнора - но оно будет только одно "id")

2022-05-02 22:34 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/database/links/LinkDAOImplTest.java
> +        Customer existingCustomer = customerDAO.saveCustomer(new Customer());
такие операции создания "owning" объектов полезно в приватный метод выносить

2022-05-02 22:34 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/links/LinkEntity.java
> +    private String shortenedUrl;
а я вот тебе сейчас скажу шутку - что это не обязательно @-URL может быть, а только 6-значный код.
домен-то свой необязательно хранить... у тебя же все сокращенные ссылки будут такого формата

https://don-kabani-bot.heroku.com/short-url

2022-05-02 22:34 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/links/LinkEntity.java
> +    @URL
валидность URL'а лучше проверять в сервисном слое

2022-05-02 22:34 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/database/links/LinkDAOImplTest.java
> +        assertThatExceptionOfType(ConstraintViolationException.class).isThrownBy(
потенциальная проблема валидатора - а сообщение какое будет в эксепшуне?
тебе же его потом кэтчить и пользаку выводить...

2022-05-02 22:34 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/database/links/LinkDAOImplTest.java
> +        Long existingLinkId = underTest.saveLink(existingCustomer, new Link()).getId();
интересно, как так new Link() можно сохранить, а с невалидным url'ом нельзя :)

2022-05-03 11:16 UTC, DSusol commented on src/main/resources/db/changelog/changelog.sql
> +    customer      INT8,
пока решить не получилось

2022-05-03 18:25 UTC, tkachenkoas reviewed
а что там с ответом на мой вопрос про количество транзакций? :)

2022-05-03 18:25 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/customers/CustomerEntity.java
> +    private List<LinkEntity> links = new ArrayList<>();
вообще, учитывая, что ты линки в базу пишешь напрямую через свой репозиторий, а не через сохранение CustomerEntity - то можно этот дефолт убрать даже

2022-05-03 18:25 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/customers/CustomerFinder.java
> +        return customerRepository.findById(id).orElseThrow(() -> new RuntimeException("Customer was not found"));
кстати, можно кидать IlegalArgumentException - он более таргетированный по своему смыслу - ведь в обычной ситуации у тебя не вылетит этот эксепшун?

2022-05-03 18:25 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/customers/CustomerFinder.java
> +public class CustomerFinder {
ну тогда уж КастомерЭнтитиФайндер :)

2022-05-03 18:25 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/links/LinkDAOImpl.java
> +                .orElseThrow(() -> new RuntimeException("Link was not found for provided shortenedUrl"));
а вот здесь кстати возможно лучше метод интерфейса поменять на Optional<Link> - с таким посылом, что "ну не нашел я у себя - а ты уж сервис лейер, решай сам что дальше делать и какие эксепшены бросать"

2022-05-03 18:25 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/links/LinkDAOImpl.java
> +        CustomerEntity customerEntity = customerFinder.findCustomerEntityById(customer.getId());
а что там насчет проверки link.getId != null ?

2022-05-03 18:25 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/links/LinkDAOImpl.java
> +        customerEntity.setLinks(customerLinkEntities);
вот это зачем ты делаешь? без него не работает?

2022-05-03 18:25 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/links/LinkDAOImpl.java
> +        LinkEntity foundLinkEntity = findLinkEntityById(id);
мне кажется нейминг ```existingLinkEntity``` чуть получше

2022-05-03 18:25 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/links/LinkDAOImpl.java
> +        return linkRepository.findById(id).orElseThrow(() -> new RuntimeException("Link was not found"));
тоже возможно лучше сделать иллегал-аргумент-эксепшун

2022-05-03 18:25 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/database/links/LinkDAOImplTest.java
> +        existingNotSavedLink = objectFactory.getSimpleLink();
у фактори методы можно смело статическими делать - зависимостей у этого компонента быть не должно :)

также имя немного стремное -> existing, но при этом notSaved ;)

2022-05-04 10:21 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/customers/CustomerEntity.java
> +    private List<LinkEntity> links = new ArrayList<>();
CascadeType.ALL подразумевает, что эту операцию делать не надо - и что у тебя CustomerEntity будет управлять добавлением-удалением ссылок...

```
linkRepository.save(linkEntityToSave)
```

смотри - какого поведения я хочу добиться: если у тебя уже миллион ссылок, до добавляя миллион-первую, тебе не надо сначала загружать первый миллион из базы...

2022-05-04 10:21 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/customers/CustomerEntityFinder.java
> +        return customerRepository.findById(id)
кстати, почитай ещё, чем отличается findById от ```T getById(ID id); ``` и что такое дб-референс :)

мне кажется, что там вообще нужно пользоваться именно getById

2022-05-04 10:21 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/links/LinkDAOImpl.java
> +        return (optionalLinkEntity.isEmpty())
открываем документацию Optional#map и изучаем :)

2022-05-04 10:21 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/links/LinkDAOImpl.java
> +        LinkEntity existingLinkEntity = linkRepository.findById(id)
а чем тебя не устраивал ``` void deleteById(ID id); ``` кстати?

2022-05-04 10:21 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/links/LinkDAOImpl.java
> +        CustomerEntity existingCustomerEntity = existingLinkEntity.getCustomer();
это неверно. чтобы удалить одну из миллиона ссылок, не нужно их все грузить в память.

2022-05-04 10:21 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/database/SimpleTestObjectFactory.java
>  @Component
компонент убери тогда :)

2022-05-06 15:32 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/customers/CustomerDAO.java
> +    void deleteAll();
я очень не уверен, что в приложении будет такая функция :)

2022-05-06 15:34 UTC, tkachenkoas commented on src/main/java/com/learning/urlshortener/database/links/LinkDAO.java
> +    void deleteAll();
очень сомневаюсь, что в приложении будет нужна такая операция :)

2022-05-06 15:39 UTC, tkachenkoas commented on src/test/java/com/learning/urlshortener/database/customers/CustomerDAOImplTest.java
> +        linkDAO.deleteAll();
не стоит добавлять логику в приложение, чтобы использовать её только в тестах.

если хочешь почистить всю базу, сделай автовайред на JDBCTempate а потом используй JDBCUtils.cleanTables (или как-то так метод называется...)

ну или CustomerEntityRepository & LinkEntityRepository заинжекть и через них напрямую...

в целом, это можно вынести даже в BaseDBTest

2022-05-06 15:40 UTC, tkachenkoas commented on src/test/resources/application-test.properties
> +logging.level.org.hibernate.engine.transaction.internal.TransactionImpl=debug
о, вот оно как делается... :) увидел логи транзакций? скрин можешь закинуть поглядеть?

спизджу у тебя конфиг

2022-05-06 22:13 UTC, tkachenkoas approved these changes
мердж!
но только поищи в настройках "enable squash" чтобы в мастер при мердже только один коммит пришел

а ещё поищи настройку, чтобы смерженные ветки автоудалялись

2022-05-07 08:29 UTC, merged